#!/bin/bash
version=$(date +%s)
	echo "var version=\"$version\";" >app.js
	find ./app -name '*.js' | xargs cat >>app.js
	rm -f lib.js
	find ./lib -name '*.js' | xargs cat >>lib.js
	echo "var version=\"$version\";" >wkr.js
	find ./wkr -name '*.js' | xargs cat >>wkr.js
	git add .
	git commit -m .
	git push
	echo $version
