#!/bin/bash
version=$(date +%s)
echo "var version=\"$version\";" >version.txt
cp version.txt index.js
cat index/*.js >>index.js
cp version.txt service.js
cat service/*.js >>service.js
git add .
git commit -m .
git push
cat version
