#!/bin/bash

version=$(date +%s)

echo "var version=$version" >index.js
cat index/*.js >>index.js

echo "var version=$version" >service.js
cat service/*.js >>service.js

git add .
git commit -m .
git push
